### ISSUE TITLE
Idea: Get native widgets depending on platform

### ISSUE THREAD

**Issue by henry2man** [juliansteenbakker/flutter_settings_ui#2]
I think it would be great if we had the possibility to have settings with the aspect of each platform. For example, I am now working with Windows and FluentUI (https://pub.dev/packages/fluent_ui), so having a native out-of-the-box look would be great. And there are other similar packages for Linux or MacOS like https://pub.dev/packages/yaru or https://pub.dev/packages/macos_ui

In other projects I think that what is usually done is to have child subprojects that implement the UI depending on the platform.

What do you think?

**Comment by juliansteenbakker** [comment]
Sounds good to me! I however don't have time to implement this myself, but i am open for PR's!

**Comment by juliansteenbakker** [comment]
This project will be closed since all functions are now available on the original package https://pub.dev/packages/settings_ui
