### ISSUE TITLE
Update design to iOS 15

### ISSUE THREAD

**Issue by cirediew** [juliansteenbakker/flutter_settings_ui#5]
The current design is based on iOS 14 it would be nice if it could be updated to the iOS 15 design.
Rounded corners, margin left and right.

![image](https://user-images.githubusercontent.com/9058616/146343030-83c180a4-1dea-4874-9294-c9f69f364e48.png)
 
Or even better take into account which version to display.

```
SettingsTile(
    ...
    this.iosVersion = 15 // default to 15 in the constructor
    ...
)
```

**Comment by juliansteenbakker** [comment]
This project will be closed since all functions are now available on the original package https://pub.dev/packages/settings_ui
