### ISSUE TITLE
onPressed not working in iOS

### ISSUE THREAD

**Issue by evanblasband** [juliansteenbakker/flutter_settings_ui#8]
I've implemented this package and on android everything seems good.  However on iOS, it does not seem that the `onPressed` method is working or getting called and same with the `onToggle` method.  Has anyone else experienced this or confirm that it is working for them on iOS? I am using version `2.0.1`, `flutter version 2.5.3`, and `iOS 15`

this is my implementation:
```dart
SettingsList(
      contentPadding: EdgeInsets.all(0),
      sections: [
        SettingsSection(
          title: 'Security',
          titleTextStyle: titleTextStyle,
          tiles: [
            SettingsTile(
              title: 'ID Method',
              subtitle: bio! ? 'Biometric' : 'Pin',
              leading: Icon(Icons.perm_identity_sharp),
              trailing: Icon(Icons.arrow_right),
              onPressed: (BuildContext context) {
                Navigator.push(
                  context,
                  MaterialPageRoute(
                    builder: (context) => ChangeIdPage(),
                  ),
                );
              },
            ),
...
```

**Comment by juliansteenbakker** [comment]
This project will be closed since all functions are now available on the original package https://pub.dev/packages/settings_ui
